version: 3.7
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: erkhuy/php-fpm:7.4
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:var/www/
    networks:
      - laravel
  nginx:
    image: nginx:1.17-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel
  database:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - SERVICE_TAG=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel

